services:
  #frontend container
  server:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    depends_on:
      - eshop_db
      - orders_db
    environment:
      - DB_HOST=eshop_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=asterinos
      - DB_NAME=eshop_db
      - ORDERS_DB_HOST=orders_db
      - ORDERS_DB_PORT=5432
      - ORDERS_DB_USER=postgres
      - ORDERS_DB_PASSWORD=asterinos
      - ORDERS_DB_NAME=orders_db
    volumes:
      - ./keycloak.json:/usr/src/app/keycloak.json

  #container for eshop_db api
  #adding env for kafka
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=eshop_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=asterinos
      - DB_NAME=eshop_db
      # this is new for kafka
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC_ORDER=order-topic
    depends_on:
      - eshop_db
    # this is new for kafka
    networks:
      - kafka_network

  #container for orders_db api
  #adding env for kafka
  api2:
    build:
      context: ./api2
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=orders_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=asterinos
      - DB_NAME=orders_db
      # this is new.
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC_ORDER=order-topic
    depends_on:
      - orders_db
    # this is new for kafka
    networks:
      - kafka_network

  #container for eshop_db
  eshop_db:
    image: postgres:17
    container_name: eshop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asterinos
      POSTGRES_DB: eshop_db
    volumes:
      - eshop_db_data:/var/lib/postgresql/data
      - ./init_eshop_db.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "5432:5432"

  #container for orders_db
  orders_db:
    image: postgres:17
    container_name: orders_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asterinos
      POSTGRES_DB: orders_db
    volumes:
      - orders_db_data:/var/lib/postgresql/data
      - ./init_orders_db.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "5433:5432"  
    
  #container for the keycloak and   
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_DATABASE: keyclo ak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
    command:
      start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    volumes:
      - ./realms:/opt/keycloak/data/import
    

  keycloak_db:
    image: postgres:17
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  # containers for kafka/zookeeper
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka_network 

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes" #temporary 

networks:
  kafka_network:

volumes:
  eshop_db_data:
  orders_db_data:
  keycloak_db_data:
  